### ISSUE TITLE
Question:  Is there any danger of name clashing when using this library along with code that uses C11 standard thread?

### ISSUE THREAD

**Issue by Rickodesea** [tinycthread/tinycthread#63]
This is a question.
Is there any danger of name clashing when using this library along with code that uses C11 standard thread?
Based my research, C11 standard threads is a long off from being ready and some compilers do not support it.  I'm not sure
if the user has to include a library for it as well to compile.  But, my question is in regards to the future - when C11 threads is properly standardized; would there be a clash with this library since it uses the exact same naming ?

For now, I am using this library 😉.

**Comment by MarcusJohnson91** [comment]
What do you mean by “properly standardized”? It’s part of C11, it’s just optional so Microsoft doesn’t have to implement it.

**Comment by gyrovorbis** [comment]
Microsoft Visual Studio just barely released support for C11 threads:
https://devblogs.microsoft.com/cppblog/c11-threads-in-visual-studio-2022-version-17-8-preview-2/

I still use this library for other platforms, though, like the Playstation Vita and PSP... I'm a Dreamcast developer, mostly, but we have native C11 threads there. I'm also targetting MacOS and iOS, but I forget whether they have native C11 threads or not... Oh, and I guess my webasm builds need this library still, as it only supports pthreads...

On my own fork I am basically `#ifdef`-ing the library out and am just including the standard C11 threads on platforms that support them natively. Otherwise, sure, there would be a clash if you were to include the C11 thread header along with this one...

**Comment by Rickodesea** [comment]
> What do you mean by “properly standardized”? It’s part of C11, it’s just optional so Microsoft doesn’t have to implement it.

Exactly what I mean, there isn't much support for it not just on Microsoft.
Same reason why I am sticking to C99 currently.

**Comment by Rickodesea** [comment]
> Microsoft Visual Studio just barely released support for C11 threads: https://devblogs.microsoft.com/cppblog/c11-threads-in-visual-studio-2022-version-17-8-preview-2/
> 
> I still use this library for other platforms, though, like the Playstation Vita and PSP... I'm a Dreamcast developer, mostly, but we have native C11 threads there. I'm also targetting MacOS and iOS, but I forget whether they have native C11 threads or not... Oh, and I guess my webasm builds need this library still, as it only supports pthreads...
> 
> On my own fork I am basically `#ifdef`-ing the library out and am just including the standard C11 threads on platforms that support them natively. Otherwise, sure, there would be a clash if you were to include the C11 thread header along with this one...

Awesome! Thanks for answer, I appreciate it.
When you use #ifdef what do you check for ?  Do you check for the existence of the C11 library.
I guess in this case it makes perfect sence that the library has the same syntax.  Your code base wouldn't change and you just conditional include from the standard library or this library.
